name: "Pull Request Labeler"
on:
- pull_request

jobs:
  triage:
    if: github.repository == 'disease-sh/API'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
