name: Lint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint
  unittests:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        node-version: [13.x]
        redis-version: [5]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start redis server
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: ${{ matrix.redis-version }}  
      - run: npm install
      - run: npm test
        
