name: Unittest
on:
  push:
    branches: [master, docker-dev]
  pull_request:
    branches: [master, docker-dev]
  schedule:
    - cron: "0 */2 * * *"
jobs:
  unittests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [5]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - uses: zcong1993/setup-timezone@master
        with:
          timezone: America/Denver
      - name: Start redis server
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - run: npm install
      - run: npm run docker-test
